<?php

require_once __DIR__ . '/classes/Config.php';
require_once __DIR__ . '/classes/SessionManager.php';
require_once __DIR__ . '/classes/Utility.php';
require_once __DIR__ . '/classes/Query.php';
require_once __DIR__ . '/classes/WebHandler.php';

function main()
{
    // Initialize configuration
    \MultiDbSqlTool\Config::initialize(__DIR__ . '/config.php');

    $templateFunction = function ($vars) {
        extract($vars);
        ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $appName . ' ' . $version; ?><?php echo ' ' . $optionalName; ?></title>
  <link rel="icon" type="image/svg+xml" href="favicon.svg">
  <link rel="alternate icon" href="favicon.ico">

  <!-- CSS Libraries -->
  <link href="//cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.min.css" rel="stylesheet">
  <link href="//cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">
  <link href="//cdn.jsdelivr.net/npm/codemirror@5.65.16/lib/codemirror.min.css" rel="stylesheet">
  <link href="//cdn.jsdelivr.net/npm/codemirror@5.65.16/theme/eclipse.min.css" rel="stylesheet">

  <!-- AG Grid -->
  <link href="//cdn.jsdelivr.net/npm/ag-grid-community@31.0.0/styles/ag-grid.min.css" rel="stylesheet">
  <link href="//cdn.jsdelivr.net/npm/ag-grid-community@31.0.0/styles/ag-theme-alpine.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="assets/app.css" rel="stylesheet">
  <link href="assets/codemirror-fix.css" rel="stylesheet">
</head>
<body>

  <div class="container-fluid app-container">
    <!-- header -->
    <div class="header">
      <h1>
        <img src="favicon.svg" alt="logo" class="app-logo">
        <?php echo $appName . ' ' . $version; ?>
        <span class="optional-name"><?php echo ' ' . $optionalName; ?></span>
      </h1>

      <div class="header-controls">
        <select id="cluster-selector" class="form-select form-select-sm me-2">
          <?php
            foreach ($clausterList as $clusterName) {
              echo "<option value=\"{$clusterName}\">{$clusterName}</option>";
            }
          ?>
        </select>

        <? if ($readOnlyMode): ?>
        <span class="badge bg-warning mode-name">Read Only</span>
        <? else: ?>
        <span class="badge bg-danger mode-name">Write Enabled</span>
        <? endif; ?>
      </div>
    </div>

    <div class="row app-content">
      <!-- sidebar -->
      <div class="col-2 left-pane sidebar">
        <!-- Table list -->
        <div class="sidebar-section">
          <div id="sidebar-tabs" class="sidebar-tabs" role="tablist">
            <button class="sidebar-tab active" type="button" data-target="stab-1" role="tab">TABLE LIST</button>
            <button class="sidebar-tab" type="button" data-target="stab-2" role="tab">DB LIST
              <span class="badge bg-secondary" id="db-count">0</span>
              <span id="db-has-error"></span>
            </button>
          </div>

          <div id="sidebar-content" class="sidebar-content">
            <div class="tab-pane" id="stab-1" role="tabpanel">
              <div id="table-list" class="table-list">
                <!-- Table items will be generated by JavaScript -->
                <!--
                <div class="table-item">
                  <div class="table-physical-name">introduced_user_profile_header</div>
                  <div class="table-logical-name">Introduced User Profile Header (Unique)</div>
                </div>
                -->
              </div>
            </div>

            <div class="tab-pane" id="stab-2" role="tabpanel">
              <select id="db-selector" class="form-select form-select-sm mb-2" multiple>
                <!-- Database options will be generated by JavaScript -->
                <!--
                <option value="shard1">shard1</option>
                <option value="shard2">shard2</option>
                -->
              </select>
            </div>
          </div>
        </div>
      </div>

      <!-- right pane -->
      <div class="col-10 right-pane">
        <!-- Editor Container -->
        <div class="editor-container">

          <!-- Editor Toolbar -->
          <div class="editor-toolbar">
            <div class="toolbar-left">
              <!-- Open dialog and restore SQL in history to editor -->
              <button id="btn-history" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#sql-history">
                <i class="bi bi-clock-history"></i> History
              </button>
            </div>
            <div class="toolbar-center">
              <!-- Use sql-formatter to clean SQL on editor -->
              <button id="btn-format" class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-code"></i> Beautify SQL
              </button>
              <!-- Execute SQL, Ctrl+Enter also fires this event -->
              <!-- When event is triggered, confirmation modal will be shown -->
              <!-- Confirmation modal will ask for user confirmation before executing SQL -->
              <button id="btn-execute" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#execution-confirm">
                <i class="bi bi-play-fill"></i> Run (Ctrl+Enter)
              </button>
            </div>
            <div class="toolbar-right">
              <!-- Export CSV/XLSX by SheetJS -->
              <span class="me-2">Export</span>
              <button id="btn-export-csv" class="btn btn-outline-success btn-sm me-1">CSV</button>
              <button id="btn-export" class="btn btn-outline-success btn-sm">XLSX</button>
            </div>
          </div>

          <!-- SQL Editor -->
          <div class="sql-editor-container">
            <!-- Initialized with CodeMirror -->
            <div id="sql-editor"></div>
          </div>

        </div>

        <!-- Result Container -->
        <div class="result-container">
          <!-- Results Tabs -->
          <div class="results-tabs-container">
            <button class="tab-nav-btn tab-nav-left" id="tab-nav-left">
              <i class="bi bi-chevron-left"></i>
            </button>

            <div id="results-tabs" class="results-tabs" role="tablist">
              <!-- Tabs will be generated by JavaScript -->
              <!-- Format: Query X (Y) , X: Number of query, Y: found rows -->
              <!--
              <button class="results-tab active" type="button" data-target="tab-1" role="tab"><i class="bi bi-check-circle"></i> Query 1 (10)</button>
              <button class="results-tab error" type="button" data-target="tab-2" role="tab"><i class="bi bi-exclamation-triangle"></i> Query 2 (0)</button>
              -->
            </div>

            <button class="tab-nav-btn tab-nav-right" id="tab-nav-right">
              <i class="bi bi-chevron-right"></i>
            </button>
          </div>

          <!-- Results Grid -->
          <div id="results-content" class="results-content">
            <!-- Default view -->
            <div class="p-4 text-center text-muted">
              <i class="bi bi-database" style="font-size: 3rem; opacity: 0.3;"></i>
              <p class="mt-3">Results shown here.</p>
            </div>

            <!-- Tab panes will be generated JavaScript -->
            <!--
            <div class="tab-pane" id="tab-3" role="tabpanel">
              <div class="error-list">
                <div class="alert alert-danger align-items-center sql-error" role="alert">
                  <strong>ERROR [shard1]</strong> syntax error at or near "FROM"
                </div>
                <div class="alert alert-danger align-items-center sql-error" role="alert">
                  <strong>ERROR [shard1]</strong> syntax error at or near "FROM"
                </div>
                <div class="alert alert-danger align-items-center sql-error" role="alert">
                  <strong>ERROR [shard1]</strong> syntax error at or near "FROM"
                </div>
              </div>
            </div>
            -->
          </div>

        </div>
      </div>
    </div>
  </div>


  <!-- Modal: Alert Dialog -->
  <div class="modal fade" id="alert-dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="alert-dialog-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="alert-dialog-label"></h1>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">OK</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal: SQL Execution Confirmation -->
  <div class="modal fade" id="execution-confirm" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="execution-confirm-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="execution-confirm-label">🔥Confirm!</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          SQLs will be executed to all databases.<br>
          If updating queries are included, data will be modified.<br>
          Are you sure to execute these SQLs?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x"></i> Cancel</button>
          <button type="button" class="btn btn-primary" id="btn-confirm-execute"><i class="bi bi-play-fill"></i> Execute</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal: SQL History -->
  <div class="modal fade" id="sql-history" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="sql-history-label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="sql-history-label">📝SQL History</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x"></i> Cancel</button>
        </div>
      </div>
    </div>
  </div>


  <!-- JavaScript Libraries -->
  <script src="//cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/codemirror@5.65.16/lib/codemirror.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/codemirror@5.65.16/mode/sql/sql.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/ag-grid-community@31.0.0/dist/ag-grid-community.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sql-formatter@15.6.8/dist/sql-formatter.min.js"></script>

  <script>
    window.MultiDbSql = {
      appShortName: '<?php echo $appShortName; ?>',
      appShortNameLower: '<?php echo $appShortNameLower; ?>',
      version: '<?php echo $version; ?>',
      isReadOnlyMode: <?php echo $readOnlyMode ? 'true' : 'false'; ?>,
    };
  </script>

  <!-- Custom JavaScript -->
  <script src="assets/app.js"></script>
</body>
</html>
        <?php
    };
    // Handle web requests
    $webHandler = new \MultiDbSqlTool\WebHandler();
    $webHandler->execute($templateFunction);
}

main();
